name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Prepare Nuxt
        run: pnpm postinstall
        
      - name: Run ESLint
        run: pnpm exec eslint .

  unit-test:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run unit tests with coverage
        run: pnpm test:unit:coverage
      
      - name: Upload unit test coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 5

  e2e-test:
    name: E2E Tests
    needs: lint
    runs-on: ubuntu-latest
    environment: integration
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8'
          
      - name: Install dependencies
        run: pnpm install
      
      - name: Install Playwright browsers
        run: pnpm playwright:install
        
      - name: Run E2E tests
        run: pnpm test:e2e
        env:
          NUXT_PUBLIC_SUPABASE_URL: ${{ secrets.NUXT_PUBLIC_SUPABASE_URL }}
          NUXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NUXT_PUBLIC_SUPABASE_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
          E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
      
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e/results/
          retention-days: 5

  status-comment:
    name: Status Comment
    if: ${{ success() }}
    needs: [unit-test, e2e-test]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Add PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-status
          message: |
            ✅ All checks have passed successfully!
            
            - ✓ Lint check passed
            - ✓ Unit tests passed
            - ✓ E2E tests passed
            
            This PR is ready for review.
